version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes: # 必要に応じて追加
      - ./backend:/app
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes: # 必要に応じて追加
      - ./frontend:/app